# Generated by Django 3.0.4 on 2020-03-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=100)),
                ('book_picture', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('price_old', models.FloatField()),
                ('author', models.CharField(max_length=50)),
                ('isbn', models.CharField(max_length=20)),
                ('press', models.CharField(max_length=50)),
                ('rest', models.IntegerField()),
                ('kind_id', models.IntegerField()),
                ('kind_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=10000)),
                ('sales', models.IntegerField()),
            ],
        ),
    ]
