# Generated by Django 3.0.4 on 2020-03-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('author', models.CharField(max_length=50)),
                ('isbn', models.CharField(max_length=20)),
                ('press', models.CharField(max_length=50)),
                ('on_sale', models.BooleanField()),
            ],
        ),
    ]
