# Generated by Django 3.0.4 on 2020-03-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='875577407@qq.com', max_length=50),
            preserve_default=False,
        ),
    ]
