# Generated by Django 2.2.11 on 2020-03-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('sum_price', models.FloatField()),
                ('status', models.IntegerField()),
                ('time_submit', models.DateTimeField()),
                ('time_pay', models.DateTimeField(null=True)),
                ('time_finish', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('book_id', models.IntegerField()),
                ('number', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
